name: Keploy Cloud API Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-keploy-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start backend server
        run: |
          nohup npm start &
          sleep 10

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        run: |
          # Replace the APP_ID below with your actual Keploy app ID from the dashboard
          keploy test-suite --app=Gv+mBKFJRMY37UqISw== --base-path=http://localhost:5000 --cloud