name: Keploy Cloud API Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-keploy-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        run: |
          export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
          keploy test-suite \
            --app=5b8f6e57-7840-4cb8-b2e3-7b98592033ae \
            --base-path=https://b333-152-58-134-186.ngrok-free.app \
            --cloud
