name: Keploy Cloud API Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-keploy-api-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd Abroad-backend
          npm install

      - name: Start backend server
        run: |
          cd Abroad-backend
          nohup npm start &
          sleep 10

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        run: |
          cd Abroad-backend
          keploy test-suite --base-path=http://localhost:5000
